[project]
name = "storm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "dspy>=2.6.0",
    "ipykernel>=6.29.5",
    "whisper>=1.1.10",
    "youtube-search>=2.1.2",
    "yt-dlp>=2025.1.26",
]
